# Generated by Django 3.2.12 on 2022-03-25 13:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Connection',
            fields=[
                ('asn', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('isp', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('code', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('plural', models.CharField(max_length=200)),
                ('symbol', models.CharField(max_length=10)),
                ('symbol_native', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('code', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('native', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='TimeZone',
            fields=[
                ('id', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('current_time', models.CharField(max_length=200)),
                ('gmt_offset', models.IntegerField()),
                ('code', models.CharField(max_length=200)),
                ('is_daylight_saving', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('geoname_id', models.IntegerField(primary_key=True, serialize=False)),
                ('capital', models.CharField(max_length=50)),
                ('country_flag', models.URLField()),
                ('country_flag_emoji', models.CharField(max_length=10)),
                ('country_flag_emoji_unicode', models.CharField(max_length=200)),
                ('calling_code', models.CharField(max_length=10)),
                ('is_eu', models.BooleanField()),
                ('languages', models.ManyToManyField(to='geoloc.Language')),
            ],
        ),
        migrations.CreateModel(
            name='GeoLocalization',
            fields=[
                ('ip', models.GenericIPAddressField(primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=4)),
                ('continent_code', models.CharField(max_length=10)),
                ('continent_name', models.CharField(max_length=50)),
                ('country_code', models.CharField(max_length=4)),
                ('country_name', models.CharField(max_length=50)),
                ('region_code', models.CharField(max_length=4)),
                ('region_name', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('zip', models.CharField(max_length=50)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('connection', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='geoloc.connection')),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='geoloc.currency')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='geoloc.location')),
                ('time_zone', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='geoloc.timezone')),
            ],
        ),
    ]
